version: '2'

services:
  meeting_service:
    image: triztiz/meeting_service:latest
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
#    volumes:
#      - ./meeting-service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://meeting_user:meeting_password@meeting_db/meeting_db_dev
      - USER_SERVICE_HOST_URL=http://user_service:8000/api/v1/users/

  meeting_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_meeting:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=meeting_user
      - POSTGRES_PASSWORD=meeting_password
      - POSTGRES_DB=meeting_db_dev

  user_service:
    image: triztiz/user:latest
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
#    volumes:
#      - ./user-service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://user_user:user_password@user_db/user_db_dev
      - MEETING_SERVICE_HOST_URL=http://meeting_service:8000/api/v1/meetings/

  user_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_user:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user_user
      - POSTGRES_PASSWORD=user_password
      - POSTGRES_DB=user_db_dev

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user_service
      - meeting_service

volumes:
  postgres_data_meeting:
  postgres_data_user: