apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: meeting-service
  name: meeting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: meeting-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: meeting-service
    spec:
      containers:
      - args:
        - uvicorn
        - app.main:app
        - --reload
        - --host
        - 0.0.0.0
        - --port
        - "8000"
        env:
        - name: DATABASE_URI
          value: postgresql://meeting_user:meeting_password@meeting-db:5432/meeting_db_dev
        - name: USER_SERVICE_HOST_URL
          value: http://user-service:8000/api/v1/users/
        image: triztiz/meeting_service:latest
        imagePullPolicy: ""
        name: meeting-service
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
