apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: meeting-db
  name: meeting-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: meeting-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: meeting-db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: meeting_db_dev
        - name: POSTGRES_PASSWORD
          value: meeting_password
        - name: POSTGRES_USER
          value: meeting_user
        image: postgres:12.1-alpine
        imagePullPolicy: ""
        name: meeting-db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: postgres-data-meeting
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: postgres-data-meeting
        persistentVolumeClaim:
          claimName: postgres-data-meeting
status: {}
