apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {
      listen 8080;

      location /api/v1/meetings {
        proxy_pass http://meeting-service:8000/api/v1/meetings;
      }

      location /api/v1/users {
        proxy_pass http://user-service:8000/api/v1/users;
      }

    }